@startuml

package internal/core/sudoku{
annotation internal/core/sudoku {
+NewGetDriverMatrixUseCase(repo Repo, user User): *GetDriverMatrixUseCase
+NewGetTeamMatrixUseCase(repo Repo, user User): *GetTeamMatrixUseCase
}

class GetDriverMatrixUseCase {
+Repo: Repo
+User: User
+Run(ctx Context): MatrixDrivers, error
}

class GetTeamMatrixUseCase {
+Repo: Repo
+User: User
+Run(ctx Context): MatrixTeams, error
}
}

package internal/models{

class Driver {
+Id: Uuid
+Name: string
+Birthday: string
+Nationality: string

}

class DriverStats {
+Driver: Driver
+TotalRaces: int
+TotalWins: int
+TotalPodiums: int
+TotalPoints: int
+TotalPoles: int
+BestFinish: int
+BestQualifying: int
+ChampionshipWins: int
+BestChampionshipPosition: int
}

class SudokuCondition {
+Label: string
+Field: string
+Op: ConditionOperator
+Value: int

}
class MatrixTeams {
+Field: [][][]Team
+ConditionSpecs: [][]SudokuCondition

}

class MatrixDrivers {
+Field: [][][]Driver
+ConditionSpecs: [][]SudokuCondition

}

class Team {
+Id: Uuid
+Name: string
+Country: string

}
class TeamStats {
+Team: Team
+TotalRaces: int
+TotalWins: int
+TotalPodiums: int
+TotalPoints: int
+TotalPoles: int
+BestFinish: int
+BestQualifying: int
+ChampionshipWins: int
+BestChampionshipPosition: int
}

}
package internal/repository{
class Repository {
+Pool: *Pool
+GetDriverStats(driver Driver): DriverStats, error
+GetTeamStats(team Team): TeamStats, error
}
}

"GetDriverMatrixUseCase" -d-> "MatrixDrivers"
"GetTeamMatrixUseCase" -d-> "MatrixTeams"
"MatrixDrivers" -d-> "Driver"
"MatrixDrivers" -d-> "SudokuCondition"
"MatrixTeams" -d-> "Team"
"MatrixTeams" -d-> "SudokuCondition"
"DriverStats" -d-> "Driver"
"TeamStats" -d-> "Team"
"GetDriverMatrixUseCase" -d-> "Repository"
"GetTeamMatrixUseCase" -d-> "Repository"
"Repository" -d-> "DriverStats"
"Repository" -d-> "TeamStats"

@enduml